package com.ss.schedulesys.domain;
// Generated Feb 11, 2017 7:27:59 PM by Hibernate Tools 5.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * CompanyContact generated by hbm2java
 */

@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "company_contact", catalog = "schedulesys_db", uniqueConstraints = @UniqueConstraint(columnNames = "phone_number"))
public class CompanyContact implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9070981035323071744L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "company_id", nullable = false, foreignKey = @ForeignKey(name = "fk_companycontact_company"))
	private CareCompany careCompany;
	
	@Size(min = 2, max = 50)
	@Column(name = "first_name", nullable = false, length = 50)
	private String firstName;
	
	@Size(min = 2, max = 50)
	@Column(name = "last_name", nullable = false, length = 50)
	private String lastName;
	
	@Size(min = 2, max = 50)
	@Column(name = "title", nullable = false, length = 50)
	private String title;
	
	@Size(min = 10, max = 10)
	@Column(name = "phone_number", unique = true, nullable = false, length = 10)
	private String phoneNumber;
	
	@Size(min = 10, max = 10)
	@Column(name = "fax", nullable = false, length = 10)
	private String fax;

}