package com.ss.schedulesys.domain;
// Generated Feb 11, 2017 7:27:59 PM by Hibernate Tools 5.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * PhoneNumber generated by hbm2java
 */
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "phone_number", catalog = "schedulesys_db", uniqueConstraints = @UniqueConstraint(columnNames = "number"))
public class PhoneNumber implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "employee_id", nullable = false, foreignKey = @ForeignKey(name = "fk_phonenumber_employee"))
	private Employee employee;
	
	@Size(min = 10, max = 10)
	@Column(name = "number", unique = true, nullable = false, length = 45)
	private String number;
	
	@Column(name = "label", nullable = false, length = 45)
	private String label;
	
	@Column(name = "type", nullable = false, length = 45)
	private String type;
	
	@JsonProperty("phoneNumber")
	public void setNumber(String number){
		this.number = number;
	}

	@JsonProperty("numberType")
	public void setType(String type){
		this.type = type;
	}
}
