package com.ss.schedulesys.domain;
// Generated Feb 11, 2017 7:27:59 PM by Hibernate Tools 5.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Test generated by hbm2java
 */
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"testOccurrences", "testSubcategories"})
@EqualsAndHashCode(exclude = {"testOccurrences", "testSubcategories"})
@Table(name = "test", catalog = "schedulesys_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Test implements java.io.Serializable {

	private static final long serialVersionUID = 216735509081039258L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@Size(min = 2, max = 50)
	@Column(name = "name", unique = true, nullable = false, length = 50)
	private String name;
	
	@Column(name = "has_completion_date", nullable = false)
	private boolean hasCompletionDate;
	
	@Column(name = "has_expiry_date", nullable = false)
	private boolean hasExpiryDate;
	
	@Column(name = "can_be_waived", nullable = false)
	private boolean canBeWaived;
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
	private Set<TestOccurrence> testOccurrences = new HashSet<TestOccurrence>(0);
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
	private Set<TestSubcategory> testSubcategories = new HashSet<TestSubcategory>(0);

}
