package com.ss.schedulesys.domain;
// Generated Feb 11, 2017 7:27:59 PM by Hibernate Tools 5.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * TestSubcategory generated by hbm2java
 */
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"testOccurrences"})
@EqualsAndHashCode(exclude = {"testOccurrences"})
@Table(name = "test_subcategory", catalog = "schedulesys_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class TestSubcategory implements java.io.Serializable {

	
	private static final long serialVersionUID = -978768629628888386L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "test_id", nullable = false, foreignKey = @ForeignKey(name = "fk_testsubcategory_test"))
	private Test test;
	
	@Size(min = 2, max = 45)
	@Column(name = "name", unique = true, nullable = false, length = 45)
	private String name;
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "testSubcategory")
	private Set<TestOccurrence> testOccurrences = new HashSet<TestOccurrence>(0);

}
