package com.ss.schedulesys.domain;
// Generated Feb 11, 2017 7:27:59 PM by Hibernate Tools 5.0.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * UserRole generated by hbm2java
 */
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"scheduleSysUsers"})
@EqualsAndHashCode(exclude = {"scheduleSysUsers"})
@Table(name = "user_role", catalog = "schedulesys_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class UserRole implements java.io.Serializable {
	
	private static final long serialVersionUID = -2757192557227893637L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Size(min = 2, max = 45)
	@Column(name = "name", unique = true, nullable = false, length = 45)
	private String name;
	
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	private Set<ScheduleSysUser> scheduleSysUsers = new HashSet<ScheduleSysUser>(0);

}
